#Definition Namespace für alle Ressourcen
apiVersion: v1
kind: Namespace
metadata:
  name: JSVAR_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucadministration
  labels:
    app: ucadministration
  namespace: JSVAR_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucadministration
  template:
    metadata:
      labels:
        app: ucadministration
    spec:
      containers:
      - name: ucadministration
        image: JSVAR_DOCKERIMAGE
        env:
        - name: UC_CUSTOMER
          value: JSVAR_UC_CUSTOMER
        - name: UC_DBNAME
          value: JSVAR_UC_DBNAME
        - name: UC_DBUSER
          value: JSVAR_UC_DBUSER
        - name: UC_DBDB
          value: JSVAR_UC_DBDB
        - name: UC_DBPSWD
          value: JSVAR_UC_DBPSWD
        - name: UC_DOMAIN
          value: JSVAR_UC_DOMAIN
---  
apiVersion: v1
kind: Service
metadata:
  name: ucadministration-service
  namespace: JSVAR_NAMESPACE
spec:
  type: NodePort
  selector:
    app: ucadministration
  ports:
  - protocol: TCP
    port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ucadministration-ingress
  namespace: JSVAR_NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /JSVAR_NAMESPACE/ucadministration/(.*)
          backend:
            serviceName: ucadministration-service
            servicePort: 80
