apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucadministration
  labels:
    app: ucadministration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucadministration
  template:
    metadata:
      labels:
        app: ucadministration
    spec:
      containers:
      - name: ucadministration
        image: JSVAR_DOCKERIMAGE
        env:
        - name: UC_DBNAME
          value: mysquc-service
        - name: UC_DBUSER
          value: root
        - name: UC_DBDB
          value: testdb
        - name: UC_DBPSWD
          value: Philipp1
        - name: UC_DOMAIN
          value: http://hhz.regel-it.de
---  
apiVersion: v1
kind: Service
metadata:
  name: ucadministration-service
spec:
  type: NodePort
  selector:
    app: ucadministration
  ports:
  - protocol: TCP
    port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ucadministration-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /ucadministration/(.*)
          backend:
            serviceName: ucadministration-service
            servicePort: 80
